# Allow build scripts only for these trusted native deps
onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - esbuild
  - vue-demi
minimumReleaseAge: 2880 # Do not release packages that have been published less than 2 days ago to avoid compromised packages from downloading